name: Chess Auto-Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  analyze-games:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          pip install requests python-chess firebase-admin google-auth

      - name: Install Stockfish 18
        run: |
          sudo wget -q https://github.com/official-stockfish/Stockfish/releases/download/sf_18/stockfish-ubuntu-x86-64-avx2.tar.gz
          sudo tar -xzf stockfish-ubuntu-x86-64-avx2.tar.gz
          sudo mv stockfish/stockfish-* /usr/local/bin/stockfish
          sudo chmod +x /usr/local/bin/stockfish

      - name: Run Analyzer Script
        env:
          CHESS_COM_USERNAME: "forgotten_gambit"
          FIREBASE_DB_URL: "https://chess-analyzer-36eb6-default-rtdb.firebaseio.com"
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: python analyzer.py
        
